<?php

$feedHost = implode('.', ['news', 'mail', 'ru']);
$feedOrigin = 'https://'.$feedHost;

return [
    'source_name' => '',
    'feed_host' => $feedHost,
    'feed_origin' => $feedOrigin,

    'feeds' => [
        [
            'url' => "{$feedOrigin}/rss/",
            'title' => 'Все новости',
            'category_slug' => 'all',
            'category_name' => 'Все новости',
            'category_color' => '#6B7280',
            'category_icon' => '📰',
        ],
        [
            'url' => "{$feedOrigin}/rss/main/",
            'title' => 'Главные новости',
            'category_slug' => 'main',
            'category_name' => 'Главные новости',
            'category_color' => '#1D4ED8',
            'category_icon' => '⭐',
        ],
        [
            'url' => "{$feedOrigin}/rss/politics/",
            'title' => 'Политика',
            'category_slug' => 'politics',
            'category_name' => 'Политика',
            'category_color' => '#DC2626',
            'category_icon' => '🏛️',
        ],
        [
            'url' => "{$feedOrigin}/rss/economics/",
            'title' => 'Экономика: Отрасли',
            'category_slug' => 'economics',
            'category_name' => 'Экономика',
            'sub_category_name' => 'Отрасли',
            'sub_category_slug' => 'otrasli',
            'category_color' => '#16A34A',
            'category_icon' => '💹',
        ],
        [
            'url' => "{$feedOrigin}/rss/society/",
            'title' => 'Общество',
            'category_slug' => 'society',
            'category_name' => 'Общество',
            'category_color' => '#9333EA',
            'category_icon' => '👥',
        ],
        [
            'url' => "{$feedOrigin}/rss/incident/",
            'title' => 'Происшествия',
            'category_slug' => 'incident',
            'category_name' => 'Происшествия',
            'category_color' => '#EA580C',
            'category_icon' => '🚨',
        ],
        [
            'url' => "{$feedOrigin}/rss/svo/",
            'title' => 'СВО',
            'category_slug' => 'svo',
            'category_name' => 'СВО',
            'category_color' => '#B45309',
            'category_icon' => '🎖️',
        ],
        [
            'url' => "{$feedOrigin}/rss/sport/",
            'title' => 'Спорт',
            'category_slug' => 'sport',
            'category_name' => 'Спорт',
            'category_color' => '#0891B2',
            'category_icon' => '⚽',
        ],
    ],

    'parser' => [
        'timeout' => 30,
        'connect_timeout' => 10,
        'batch_concurrency' => 5,
        'user_agent' => 'Mozilla/5.0 (compatible; NewsPortalBot/1.0; +http://localhost)',
        'max_items_per_feed' => 50,
        'duplicate_window_hours' => 72,
    ],

    'page_parser' => [
        'enabled' => true,
        'timeout' => 20,
        'connect_timeout' => 10,
        'max_retries' => 2,
    ],

    'source_pages' => [
        'enabled' => true,
        'timeout' => 20,
        'connect_timeout' => 10,
        'max_retries' => 2,
        'user_agent' => 'Mozilla/5.0 (compatible; NewsPortalBot/1.0; +http://localhost)',
        'min_body_characters' => 40,
        'title_selectors' => [
            'h1[itemprop="headline"]',
            '.article__title',
            'article h1',
            'main h1',
            'h1',
        ],
        'subtitle_selectors' => [
            'h2[itemprop="alternativeHeadline"]',
            '.article__subtitle',
            '.article__lead',
            '.article__deck',
            'article .subtitle',
            'main .subtitle',
        ],
        'article_selectors' => [
            '[article-item-type="html"]',
            '.article__body',
            '.article-content',
            '.entry-content',
            'article',
            'main',
        ],
        'author_selectors' => [
            '[rel="author"]',
            '[itemprop="author"]',
            '.article__author',
            '.article-author',
            'a[href*="/authors/"]',
        ],
        'image_selectors' => [
            'meta[property="og:image"]',
            'article figure img',
            '.article__media img',
            'main img',
        ],
        'remove_selectors' => [
            '.advert',
            '.ad',
            '.ads',
            '.banner',
            '.share',
            '.social',
            '.related',
            '.recommendations',
            '.article__tags',
            '.article__footer',
            '.article__meta',
            '.article__toolbar',
            '.article__buttons',
        ],
    ],

    'image' => [
        'extract_from_enclosure' => true,
        'extract_from_media_namespace' => true,
        'extract_from_description_img' => true,
        'fallback_placeholder' => null,
    ],

    'article' => [
        'auto_short_description' => true,
        'short_description_length' => 300,
        'auto_reading_time' => true,
        'words_per_minute' => 200,
        'default_status' => 'published',
        'default_author' => 'Редакция',
    ],
];
